const {signup,signin,DbRooms,AllRooms,UpdateRoom,DeleteRoomDB,contactus,allContact,findOneRoom,findAdmin,adminUpdate,admindrop,adminLogout} = require('../controller/adminController')
const express = require("express")
const router = express.Router()
const multer = require("../multer")
const AdminJWT = require("../Middleware/adminAuth")

router.post("/signup",signup)
router.post("/signin",signin)
router.get("/logout",AdminJWT,adminLogout)
router.post("/rooms",AdminJWT,multer.single("image"),DbRooms)
router.get("/allRooms",AdminJWT,AllRooms)
router.get("/room/:id",findOneRoom)
router.get("/admin/:id",AdminJWT,findAdmin)
router.put("/adminupdate/:id",AdminJWT,adminUpdate)
router.put('/roomsUpdate/:id',AdminJWT,multer.single("image"),UpdateRoom)
router.delete("/deleteDB/:id",DeleteRoomDB)
router.delete("/admindelete/:id",admindrop)
router.post("/contactus",contactus)
router.get("/allContactus",AdminJWT,allContact)

module.exports = router